---
title: "Harrow Water Content"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
library(readxl)
library(tidyverse)
library(ggthemes)
library(patchwork)
library(grid)
library(gridExtra)

windowsFonts(times = windowsFont("times new roman"))

SWC <- read_excel("data/Harrow SWC.xlsx")|> 
  mutate(Year = year(date),
         date = as.Date(date))


SWCA <- SWC |> filter(date == '2015-08-11') |> mutate(y = 0.38)
```

```{r}
y_grob = expression(bold(Soil~Water~Content~(cm^{3}/cm^{3})))

ggplot()+
  geom_line(data = SWC|> filter(Model == "dndc"), 
            mapping = aes(date, Water, col = "DNDC"), linewidth = 1) +
  geom_point(data = SWC |> filter(Model == "obs"),
             mapping = aes(date, Water, col = "Obs"), size = 2) +
  geom_text(data=SWCA, aes(x=date, y= y, label= "d = 0.7"), 
            colour="black", size = 7) +
  scale_color_manual(breaks=c('DNDC', 'Obs'),
                     values=c('DNDC'='red4', 'Obs'='blue4')) +
  facet_grid(component ~ Year, scales = "free", switch  = "both", space = "free") +
  scale_x_date(date_breaks = "7 week", date_labels = "%b")+
  scale_y_continuous(limits = c(0.07, 0.4))+
  theme_base(base_family = "times", base_size = 20) +
  theme(legend.text = element_text(face = "bold", size = 20),
        legend.position = "top",
        axis.text = element_text(face = "bold"),
        axis.title = element_text(face = "bold", size = 20),
        strip.placement = 'outside',
        strip.background.x = element_blank(),
        panel.spacing = unit(0,'lines'),
        strip.text = element_text(face="bold", size=20)) +
  labs(color = NULL, y = y_grob, x = NULL)
```
