---
title: "Soil Temperature"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
execute: 
  echo: false
  warning: false
---

```{r}
library(readxl)
library(tidyverse)
library(ggthemes)
library(patchwork)
library(gridExtra)
library(grid)

windowsFonts(times = windowsFont("times new roman"))
SoilTemp <- read_excel("data/SoilTemp.xlsx") |> 
  mutate(Year = year(Date))

Truro_2017 <- SoilTemp |> filter(Site != "Montreal", Year == 2017) |> 
  mutate(Date = as.Date(Date))
Truro_2018 <- SoilTemp |> filter(Site != "Montreal", Year == 2018)|> 
  mutate(Date = as.Date(Date))
Truro_2019 <- SoilTemp |> filter(Site != "Montreal", Year == 2019)|> 
  mutate(Date = as.Date(Date))


Montreal_2017 <- SoilTemp |> filter(Site == "Montreal", Year == 2017)|> 
  mutate(Date = as.Date(Date))
Montreal_2018 <- SoilTemp |> filter(Site == "Montreal", Year == 2018)|> 
  mutate(Date = as.Date(Date))
Montreal_2019 <- SoilTemp |> filter(Site == "Montreal", Year == 2019)|> 
  mutate(Date = as.Date(Date))
```

# Truro

```{r}
ST_plt <- function(Data) {
  ggplot() +
  geom_line(data = Data |> filter(Model == "DNDC"), mapping = aes(Date, temp, color = "DNDC")) +
  geom_point(data = Data |> filter(Model == "Obs"), mapping = aes(Date, temp, color = "Obs"), size = 2) +
  scale_color_manual(breaks=c('DNDC', 'Obs'),
                     values=c('DNDC'='red4', 'Obs'='blue4')) +
  scale_x_date(date_breaks = "5 week", date_labels = "%b") + 
  scale_y_continuous(breaks = seq(-10, 30, 5), limits = c(-10, 30)) +
  theme_base(base_family = "times") +
  theme(legend.text = element_text(face = "bold", size = 20),
        axis.text = element_text(face = "bold"),
        axis.title = element_text(face = "bold", size = 20))
}


pt1 <- ST_plt(Truro_2017)+
  labs(x = NULL, y = "Truro", col = NULL) +
  annotate(geom="text", x=as.Date("2017-11-11"), y=25, 
             label="d = 0.7")+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

pt2 <- ST_plt(Truro_2018) +
  labs(x = NULL, y = NULL, col = NULL)+
  annotate(geom="text", x=as.Date("2018-11-11"), y=25, 
             label="d = 0.9")+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

pt3 <- ST_plt(Truro_2019)+
  labs(x = NULL, y = NULL, col = NULL)+
  annotate(geom="text", x=as.Date("2019-11-11"), y=25, 
             label="d = 0.7")+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

```

# Montreal

```{r}
pm1 <- ST_plt(Montreal_2017) +
  labs(x = 2017, y = "Montreal", col = NULL)+
  annotate(geom="text", x=as.Date("2017-11-11"), y=25, 
             label="d = 0.7")

pm2 <- ST_plt(Montreal_2018)+
  labs(x = 2018, y = NULL, col = NULL)+
  annotate(geom="text", x=as.Date("2018-11-11"), y=25, 
             label="d = 0.7")

pm3 <- ST_plt(Montreal_2019)+
  labs(x = 2019, y = NULL, col = NULL)+
  annotate(geom="text", x=as.Date("2019-11-11"), y=25, 
             label="d = 0.7")

```

## Combined Plots

```{r}
y_grob = textGrob(expression(bold(Soil~Temperature ^{0}~C)),
                  gp=gpar(fontface="bold", fontsize=15), rot=90)

grid.arrange(patchworkGrob(((pt1|pt2|pt3)/(pm1|pm2|pm3) + 
  plot_layout(heights = c(1,1), guides = "collect")) & theme(plot.background = element_blank(),
                                                             legend.position = "top")),
  left = y_grob)
```
